- client/src/components/tools/tool.vue
- client/src/components/tools/toolMetadata.vue
> connect tools to tools jsonLD

- client/src/components/dataset/annotation.vue
- client/src/components/dataset/dataset.vue
- client/src/components/dataset/relatedData.vue
- client/src/state.js
Annotation and dataset updated, so moving to master.
> make related data vue that accessed results in prep for implementation

- client/src/components/facetsearch/Search.vue
> Fix breadcrumb 1

- .github/workflows/publish_staging_s3.yml
- client/src/api/jsonldObject.js
- client/src/components/dataset/citationButton.vue
- client/src/components/dataset/dataset.vue
> Cite metadata buttons

- client/src/components/feedback/feedback.vue
- client/src/components/help/about.vue
> change feedback email address

- client/src/components/help/about.vue
> add citation of GeoCODES on about.html

- client/src/components/facetsearch/RangeSlider.vue
> Fix slider props

- client/src/sparql_blaze/sparql_gettools_download.txt
- client/src/sparql_blaze/sparql_gettools_webservice.txt
- client/src/sparql_blaze/sparql_hastools.txt
> change sparql to use graphdb for ecrr queries

- client/src/config/development.js
- client/src/config/production.js
- client/src/config/staging.js
> Change to include encoding rather than ext

- client/src/components/facetsearch/FacetNumericRangeSlider.vue
- client/src/components/facetsearch/RangeSlider.vue
- client/src/config/development.js
> handle empty data case

- client/src/components/facetsearch/ResultItem.vue
- client/src/components/navHeader.vue
fix link
**Fixes #60**
**Fixes #53**
5 min
[
- [x ] Immediately
_Please select a relevant option:_
- [x ] Bug fix (non-breaking change which fixes an issue).
_Please select all applicable options:_
- [ x] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.
- [ x] New and existing unit tests pass locally with my changes.
> #60 getting upper-icon & dataset links to open as they did before

- client/package.json
- client/src/components/facetsearch/Search.vue
- client/src/state.js
- client/yarn.lock
> Simplecache

- client/src/api/jsonldObject.js
- client/src/config/production.js
- server/api/dataset_s3_store.js
- server/api/jsonldObject.js
- server/api/tools.js
- server/config/development.js
- server/config/geocodestest.js
- server/config/production.js
- server/config/staging.js
- server/routes/index.js
FOR SOME REASON Netlify checks. still shows up as tests, even though sites deleted, and issue is that those are the UI side of things. This is for the server side, deployable via container.
Action pass. https://github.com/earthcube/facetsearch/actions
vue-services container passing env varaibles to container in the env.beta should allow for override of the defaults.
- var bucket = process.env.BUCKET || 'gleaner'
- var bucketpath = process.env.BUCKETPATH || 'summoned'
- // options for path: bucket, bucketpath, reponame, sha
- var pathtemplate = process.env.PATHTEMPLATE || '${bucketpath}/${reponame}/${sha}.jsonld'
- // options for tool: bucket, bucketpath, reponame, ref (aka ark, or maybe a sha in the future)
- var tooltemplate = process.env.TOOLTEMPLATE || …
> Feature config s3path

- .github/workflows/docker_facet_api_node_server.yml
- .github/workflows/docker_facet_vue_client.yml
- client/src/config/production.js
- server/api/dataset_s3_store.js
- server/api/tools.js
- server/config/development.js
- server/config/geocodestest.js
- server/config/production.js
- server/config/staging.js
> Fix template mustash

- client/public/config/config.yaml
- client/src/components/dataset/dataset.vue
- client/src/state.js
toast if we do not find a jsonld
> Catch and Improve dataset error messages so toast does not always shown

- client/src/components/collection/Collection.vue
- client/src/components/collection/sendCollectionToNotebook.vue
> Fix 105 collectionmenu and notebook

- client/public/config/config.yaml
- client/src/components/facetsearch/ResultItem.vue
> Feat toolsisloading spinner

- .github/workflows/docker_facet_api_node_server.yml
- .github/workflows/docker_facet_vue_client.yml
- client/package.json
- client/public/config/config.yaml
- client/public/config/config_geocodes_1.yaml
- client/public/config/config_wifire.yaml
- client/src/api/jsonldObject.js
- client/src/components/dataset/annotation.vue
- client/src/components/dataset/citationButton.vue
- client/src/components/dataset/connectedTools.vue
- client/src/components/dataset/dataset.vue
- client/src/components/dataset/datasetLocation.vue
- client/src/components/dataset/downloadfiles.vue
- client/src/components/dataset/igsnSampleList.vue
- client/src/components/dataset/metadata.vue
- client/src/components/dataset/relatedData.vue
- client/src/state.js
- client/yarn.lock
- server/api/jsonldObject.js
> Fix jsonld w graph

- .github/workflows/docker_facet_api_node_server.yml
- .github/workflows/docker_facet_vue_client.yml
- client/.env
- client/public/config/config.yaml
- client/public/config/config_dev.yaml
- docker/docker-compose_dev.yaml
- server/api/dataset_s3_store.js
- server/api/utils.js
- server/config/services.js
#117 fix changed path.
This is done with an ENVVAR UNIVERSION=v2
> 117 master fixuri

- client/public/config/config.yaml
- client/public/config/config_dev.yaml
- client/public/config/config_geocodes_1.yaml
- client/public/config/config_prod.yaml
- client/public/config/config_wifire.yaml
- client/src/components/help/report.vue
* Adds property to config.yaml so reports can  be customized.
* * add computed to reports and about so that it can read from S3_REPORTS_URL
* Should parse json even if is has a NaN from a dataframe
> 109 dv repository summaries for about page

- .github/workflows/docker_facet_vue_client.yml
- client/src/components/dataset/dataset.vue
- client/src/sparql_blaze/sparql_query.txt
- client/src/state.js
#138 Remove minRelavance
#136 Fix label.
> #138 #136 Fix label. Remove minRelavance

- client/src/api/jsonldObject.js
- client/src/components/dataset/dataset.vue
- client/src/components/dataset/datasetLocation.vue
This fixes an issue when no JSONLD is returned.
The Box issue was to an issue with the dataset
> check for empty return

- .github/workflows/docker_facet_vue_client.yml
- client/src/components/facetsearch/RangeSlider.vue
> fix to range slider

- .github/workflows/docker_facet_vue_client.yml
- client/package.json
- client/src/components/facetsearch/Search.vue
- client/src/components/landing/landing.vue
- client/src/components/navHeader.vue
- client/src/routes.js
- client/src/sparql_blaze/sparql_query.txt
- client/src/state.js
- client/yarn.lock
> Adding checkbox for and/or option

- client/src/components/dataset/downloadfiles.vue
> removing the icon associated with collab service

- client/src/components/dataset/dataset.vue
> change button label

- client/src/components/facetsearch/FacetNumericRangeSlider.vue
> Making facet text item (publishing yr) non clickable
